import { DSMLayerConfig, DSMLayerId } from "@/types/gis";

const DSM_COORDINATES: [[number, number], [number, number], [number, number], [number, number]] = [
  [74.49454665041536, 18.16847153708153], // Top-Left [lng, lat]
  [74.51700453251834, 18.16847153708153], // Top-Right [lng, lat]
  [74.51700453251834, 18.152481525024204], // Bottom-Right [lng, lat]
  [74.49454665041536, 18.152481525024204], // Bottom-Left [lng, lat]
];

const DSM_BOUNDS: [number, number, number, number] = [
  74.49454665041536, 18.152481525024204, 74.51700453251834, 18.16847153708153
];

export const DSM_LAYERS: Record<DSMLayerId, DSMLayerConfig> = {
  farm_boundary: {
    id: "farm_boundary",
    nameKey: "dsm.layers.boundary.name",
    shortName: "Boundary",
    descriptionKey: "dsm.layers.boundary.desc",
    unit: "Cadastral",
    sourceType: "DEMO KML",
    sourceLabel: "Pune District Cadastral Survey (Malegaon Bk)",
    status: "available",
    isDefault: true,
  },
  ph: {
    id: "ph",
    nameKey: "dsm.layers.ph.name",
    shortName: "pH",
    descriptionKey: "dsm.layers.ph.desc",
    unit: "pH",
    sourceType: "DSM PREDICTION",
    sourceLabel: "Pune DSM QRF Model Prediction (Sentinel-2 + DEM)",
    status: "available",
    min: 4.5,
    max: 8.5,
    step: 0.1,
    imageUrl: "/maps/rasters/ph.png",
    imageCoordinates: DSM_COORDINATES,
    rasterBounds: DSM_BOUNDS,
    colorStops: [
      { value: 4.5, color: "#d73027", label: "Strongly Acidic (4.5)" },
      { value: 5.5, color: "#fc8d59", label: "Moderately Acidic (5.5)" },
      { value: 6.5, color: "#fee08b", label: "Slightly Acidic (6.5)" },
      { value: 7.2, color: "#91cf60", label: "Neutral / Optimal (7.0 - 7.5)" },
      { value: 8.0, color: "#4575b4", label: "Moderately Alkaline (8.0)" },
      { value: 8.5, color: "#313695", label: "Strongly Alkaline (8.5)" },
    ],
  },
  bd: {
    id: "bd",
    nameKey: "dsm.layers.bd.name",
    shortName: "BD",
    descriptionKey: "dsm.layers.bd.desc",
    unit: "g/cm³",
    sourceType: "DSM PREDICTION",
    sourceLabel: "Pune DSM Soil Bulk Density Model (0-15 cm)",
    status: "available",
    min: 1.0,
    max: 1.8,
    step: 0.05,
    imageUrl: "/maps/rasters/bd.png",
    imageCoordinates: DSM_COORDINATES,
    rasterBounds: DSM_BOUNDS,
    colorStops: [
      { value: 1.0, color: "#1a9850", label: "Low / Well Aerated (1.0)" },
      { value: 1.25, color: "#91cf60", label: "Ideal Tilth (1.2 - 1.3)" },
      { value: 1.45, color: "#fee08b", label: "Moderate Compaction (1.45)" },
      { value: 1.65, color: "#fc8d59", label: "Restricted Rooting (1.65)" },
      { value: 1.8, color: "#d73027", label: "Severe Compaction (1.8+)" },
    ],
  },
  elevation: {
    id: "elevation",
    nameKey: "dsm.layers.elevation.name",
    shortName: "DEM",
    descriptionKey: "dsm.layers.elevation.desc",
    unit: "m",
    sourceType: "DSM PREDICTION",
    sourceLabel: "Digital Elevation Model (SRTM 30m / DEM)",
    status: "available",
    min: 520,
    max: 580,
    step: 5,
    imageUrl: "/maps/rasters/elevation.png",
    imageCoordinates: DSM_COORDINATES,
    rasterBounds: DSM_BOUNDS,
    colorStops: [
      { value: 520, color: "#2c7bb6", label: "520 m (Lowland / Drainage)" },
      { value: 535, color: "#abd9e9", label: "535 m" },
      { value: 550, color: "#ffffbf", label: "550 m (Valley Plains)" },
      { value: 565, color: "#fdae61", label: "565 m" },
      { value: 580, color: "#d7191c", label: "580 m (Ridge / Uplands)" },
    ],
  },
  nitrogen: {
    id: "nitrogen",
    nameKey: "dsm.layers.nitrogen.name",
    shortName: "N",
    descriptionKey: "dsm.layers.nitrogen.desc",
    unit: "kg/ha",
    sourceType: "DSM PREDICTION",
    sourceLabel: "Pune DSM Available N Prediction (Vertisol Calibrated)",
    status: "available",
    min: 140,
    max: 450,
    step: 10,
    imageUrl: "/maps/rasters/nitrogen.png",
    imageCoordinates: DSM_COORDINATES,
    rasterBounds: DSM_BOUNDS,
    colorStops: [
      { value: 140, color: "#d7191c", label: "Deficient (< 200 kg/ha)" },
      { value: 200, color: "#fdae61", label: "Low (200 - 280 kg/ha)" },
      { value: 280, color: "#ffffbf", label: "Medium (280 - 350 kg/ha)" },
      { value: 380, color: "#a6d96a", label: "Sufficient (350 - 450 kg/ha)" },
      { value: 450, color: "#1a9641", label: "High (> 450 kg/ha)" },
    ],
  },
  soc: {
    id: "soc",
    nameKey: "dsm.layers.soc.name",
    shortName: "SOC",
    descriptionKey: "dsm.layers.soc.desc",
    unit: "%",
    sourceType: "DSM PREDICTION",
    sourceLabel: "Pune DSM Topsoil Organic Carbon Model (0-15 cm)",
    status: "available",
    min: 0.2,
    max: 1.2,
    step: 0.05,
    imageUrl: "/maps/rasters/soc.png",
    imageCoordinates: DSM_COORDINATES,
    rasterBounds: DSM_BOUNDS,
    colorStops: [
      { value: 0.2, color: "#f7f4f0", label: "Very Low (< 0.4%)" },
      { value: 0.4, color: "#e0d3c1", label: "Low (0.4 - 0.5%)" },
      { value: 0.6, color: "#bfa382", label: "Moderate (0.5 - 0.75%)" },
      { value: 0.8, color: "#8c6239", label: "Good (0.75 - 1.0%)" },
      { value: 1.2, color: "#4a2f13", label: "High Organic Reserve (> 1.0%)" },
    ],
  },
  ndvi: {
    id: "ndvi",
    nameKey: "dsm.layers.ndvi.name",
    shortName: "NDVI",
    descriptionKey: "dsm.layers.ndvi.desc",
    unit: "Index",
    sourceType: "SATELLITE DERIVED",
    sourceLabel: "Sentinel-2 Multi-temporal NDVI (10m Resolution)",
    status: "available",
    min: -0.1,
    max: 0.85,
    step: 0.05,
    imageUrl: "/maps/rasters/ndvi.png",
    imageCoordinates: DSM_COORDINATES,
    rasterBounds: DSM_BOUNDS,
    colorStops: [
      { value: -0.1, color: "#000000", label: "Water / Shadow (-0.1)" },
      { value: 0.1, color: "#a6611a", label: "Bare Soil / Fallow (0.1 - 0.2)" },
      { value: 0.3, color: "#dfc27d", label: "Emerging / Sparse (0.3 - 0.4)" },
      { value: 0.5, color: "#80cdc1", label: "Moderate Canopy (0.5 - 0.6)" },
      { value: 0.7, color: "#018571", label: "Dense / Peak Biomass (0.7+)" },
    ],
  },
  evi: {
    id: "evi",
    nameKey: "dsm.layers.evi.name",
    shortName: "EVI",
    descriptionKey: "dsm.layers.evi.desc",
    unit: "Index",
    sourceType: "SATELLITE DERIVED",
    sourceLabel: "Sentinel-2 Enhanced Vegetation Index (EVI)",
    status: "available",
    min: 0.0,
    max: 0.8,
    step: 0.05,
    imageUrl: "/maps/rasters/evi.png",
    imageCoordinates: DSM_COORDINATES,
    rasterBounds: DSM_BOUNDS,
    colorStops: [
      { value: 0.0, color: "#f7fcf5", label: "Bare / Non-vegetated (0.0)" },
      { value: 0.2, color: "#c7e9c0", label: "Low Canopy Cover (0.2)" },
      { value: 0.4, color: "#74c476", label: "Medium Biomass (0.4)" },
      { value: 0.6, color: "#238b45", label: "Dense Crop Canopy (0.6)" },
      { value: 0.8, color: "#00441b", label: "Vigorous Biomass (0.8)" },
    ],
  },
  uncertainty: {
    id: "uncertainty",
    nameKey: "dsm.layers.uncertainty.name",
    shortName: "QRF Err",
    descriptionKey: "dsm.layers.uncertainty.desc",
    unit: "% error",
    sourceType: "DSM PREDICTION",
    sourceLabel: "Quantile Regression Forest 90% Prediction Interval",
    status: "available",
    min: 0,
    max: 30,
    step: 2,
    imageUrl: "/maps/rasters/uncertainty.png",
    imageCoordinates: DSM_COORDINATES,
    rasterBounds: DSM_BOUNDS,
    colorStops: [
      { value: 5, color: "#10b981", label: "High Confidence (< 8%)" },
      { value: 12, color: "#f59e0b", label: "Moderate Precision (8 - 15%)" },
      { value: 20, color: "#ef4444", label: "Elevated Uncertainty (> 15%)" },
      { value: 30, color: "#991b1b", label: "High Error (> 25%)" },
    ],
  },
};

export const DSM_LAYER_LIST: DSMLayerConfig[] = Object.values(DSM_LAYERS);
