import { DSMLayerConfig, DSMLayerId, DSMLayerCategoryId, ColorStop } from "@/types/gis";

export interface DSMCategoryInfo {
  id: DSMLayerCategoryId;
  name: string;
  marathiName: string;
  icon: string;
}

export const DSM_CATEGORIES: DSMCategoryInfo[] = [
  {
    id: "soil_properties",
    name: "1. Soil Properties (0–30 cm Root-Zone Standardized)",
    marathiName: "१. मातीचे गुणधर्म (०-३० सेमी प्रमाणबद्ध)",
    icon: "leaf",
  },
  {
    id: "topography",
    name: "2. Topography & Elevation",
    marathiName: "२. भूरूप आणि उंची",
    icon: "mountain",
  },
  {
    id: "land_use",
    name: "3. Land Use & Multi-Spectral Indices",
    marathiName: "३. जमीन वापर आणि बहु-स्पेक्ट्रल निर्देशांक",
    icon: "satellite",
  },
];

export const DSM_LAYER_ORDER: DSMLayerId[] = [
  // 1. Soil Properties (0–30 cm Root-Zone Standardized)
  "bdod",
  "cec",
  "cfvo",
  "clay",
  "sand",
  "silt",
  "soc",
  "nitrogen",
  "ph",
  "soil_texture",

  // 2. Topography & Elevation
  "elevation",
  "slope",

  // 3. Land Use & Multi-Spectral Indices
  "lulc",
  "kharif_rgb",
  "rabi_rgb",
  "ndvi",
  "evi",
  "savi",
  "ndmi",
  "ndre",
  "bsi",
  "ndwi",

  // Boundary
  "farm_boundary",

  // Backward compatibility aliases
  "bd",
  "uncertainty",
];

// Precision Agriculture Fertility Contour Palettes matching user reference screenshot
// 8 discrete contour levels: Red (Deficient) -> Orange -> Amber -> Yellow -> Lime -> Olive -> Mid Green -> Deep Forest Green
export const CONTOUR_AGRONOMIC_COLORS = [
  "rgb(253, 35, 0)",    // 0: #fd2300 - Deep Crimson Red (Deficient / Critical)
  "rgb(253, 136, 0)",   // 1: #fd8800 - Vibrant Orange (Low)
  "rgb(254, 187, 0)",   // 2: #febb00 - Warm Golden Amber (Moderately Low)
  "rgb(253, 233, 0)",   // 3: #fde900 - Lemon Yellow (Average / Marginal)
  "rgb(222, 234, 1)",   // 4: #deea01 - Chartreuse / Lime (Good)
  "rgb(164, 196, 0)",   // 5: #a4c400 - Light Olive Green (Sufficient / High)
  "rgb(107, 161, 1)",   // 6: #6ba101 - Medium Green (Optimal)
  "rgb(50, 123, 0)",    // 7: #327b00 - Deep Forest Green (Very High / Prime)
];

export const CONTOUR_INVERTED_COLORS = [...CONTOUR_AGRONOMIC_COLORS].reverse();

export const ELEVATION_COLORS = [
  "rgb(45, 106, 79)",   // 541m - Emerald valley
  "rgb(82, 183, 136)",  // Mint lower slope
  "rgb(183, 228, 199)", // Pale green bench
  "rgb(224, 192, 151)", // Buff sand mid slope
  "rgb(212, 163, 115)", // Warm amber upper slope
  "rgb(140, 80, 35)",   // 582m - Ochre brown summit
];

export const MOISTURE_COLORS = [
  "rgb(217, 119, 6)",   // Dry amber
  "rgb(234, 179, 8)",   // Marginal yellow
  "rgb(132, 204, 22)",  // Moderate lime
  "rgb(16, 185, 129)",  // Good moisture emerald
  "rgb(6, 182, 212)",   // High moisture cyan
  "rgb(37, 99, 235)",   // Saturated blue
];

function createStopsFromColors(colors: string[], min: number, max: number): ColorStop[] {
  const span = max - min || 1;
  return colors.map((color, i) => ({
    value: Number((min + (i / (colors.length - 1)) * span).toFixed(2)),
    color,
  }));
}

function createContourStops(min: number, max: number, inverted = false): ColorStop[] {
  const colors = inverted ? CONTOUR_INVERTED_COLORS : CONTOUR_AGRONOMIC_COLORS;
  return createStopsFromColors(colors, min, max);
}

export const DSM_LAYERS: Record<DSMLayerId, DSMLayerConfig> = {
  // =========================================================================
  // 1. Soil Properties (Standardized Root-Zone)
  // =========================================================================
  bdod: {
    id: "bdod",
    name: "Bulk Density",
    shortName: "Bulk Density",
    nameKey: "dsm.layers.bdod.name",
    descriptionKey: "dsm.layers.bdod.desc",
    marathiName: "मातीची घनता",
    unit: "g/cm³",
    category: "soil_properties",
    categoryLabel: "Soil Properties",
    categoryLabelMr: "मातीचे गुणधर्म",
    sourceType: "DSM PREDICTION",
    sourceLabel: "SoilGrids Standardized",
    status: "available",
    min: 1.25,
    max: 1.6,
    mean: 1.54,
    std: 0.04,
    description: "Dry mass of soil per unit volume. Indicator of compaction, root aeration and penetration resistance.",
    colorStops: createContourStops(1.25, 1.6, true),
  },
  cec: {
    id: "cec",
    name: "Cation Exchange Capacity (CEC)",
    shortName: "CEC",
    nameKey: "dsm.layers.cec.name",
    descriptionKey: "dsm.layers.cec.desc",
    marathiName: "धनायन विनिमय क्षमता (CEC)",
    unit: "cmol(c)/kg",
    category: "soil_properties",
    categoryLabel: "Soil Properties",
    categoryLabelMr: "मातीचे गुणधर्म",
    sourceType: "DSM PREDICTION",
    sourceLabel: "SoilGrids Standardized",
    status: "available",
    min: 20.0,
    max: 42.0,
    mean: 33.4,
    std: 3.5,
    description: "Total capacity of soil to hold exchangeable cations (Ca, Mg, K). Reflects nutrient retention & fertility buffer.",
    colorStops: createContourStops(20.0, 42.0),
  },
  cfvo: {
    id: "cfvo",
    name: "Coarse Fragments",
    shortName: "Coarse Fragments",
    nameKey: "dsm.layers.cfvo.name",
    descriptionKey: "dsm.layers.cfvo.desc",
    marathiName: "जाड दगड-गोटे प्रमाण",
    unit: "%",
    category: "soil_properties",
    categoryLabel: "Soil Properties",
    categoryLabelMr: "मातीचे गुणधर्म",
    sourceType: "DSM PREDICTION",
    sourceLabel: "SoilGrids Standardized",
    status: "available",
    min: 5.0,
    max: 16.0,
    mean: 11.3,
    std: 1.8,
    description: "Volume percentage of coarse rock fragments (>2mm) in root zone. Affects tillability and water capacity.",
    colorStops: createContourStops(5.0, 16.0, true),
  },
  clay: {
    id: "clay",
    name: "Clay",
    shortName: "Clay",
    nameKey: "dsm.layers.clay.name",
    descriptionKey: "dsm.layers.clay.desc",
    marathiName: "चिकणमाती",
    unit: "%",
    category: "soil_properties",
    categoryLabel: "Soil Properties",
    categoryLabelMr: "मातीचे गुणधर्म",
    sourceType: "DSM PREDICTION",
    sourceLabel: "SoilGrids Standardized",
    status: "available",
    min: 28.0,
    max: 48.0,
    mean: 42.6,
    std: 2.8,
    description: "Clay fraction (<0.002mm) by weight in root zone. Controls water retention, swelling and shrink-swell cracking.",
    colorStops: createContourStops(28.0, 48.0),
  },
  sand: {
    id: "sand",
    name: "Sand",
    shortName: "Sand",
    nameKey: "dsm.layers.sand.name",
    descriptionKey: "dsm.layers.sand.desc",
    marathiName: "वाळू / रेती",
    unit: "%",
    category: "soil_properties",
    categoryLabel: "Soil Properties",
    categoryLabelMr: "मातीचे गुणधर्म",
    sourceType: "DSM PREDICTION",
    sourceLabel: "SoilGrids Standardized",
    status: "available",
    min: 18.0,
    max: 34.0,
    mean: 29.5,
    std: 2.1,
    description: "Sand fraction (0.05–2.0mm) in root zone. Influences drainage, aeration, and thermal conductivity.",
    colorStops: createContourStops(18.0, 34.0),
  },
  silt: {
    id: "silt",
    name: "Silt",
    shortName: "Silt",
    nameKey: "dsm.layers.silt.name",
    descriptionKey: "dsm.layers.silt.desc",
    marathiName: "गाळ",
    unit: "%",
    category: "soil_properties",
    categoryLabel: "Soil Properties",
    categoryLabelMr: "मातीचे गुणधर्म",
    sourceType: "DSM PREDICTION",
    sourceLabel: "SoilGrids Standardized",
    status: "available",
    min: 18.0,
    max: 31.0,
    mean: 27.3,
    std: 1.5,
    description: "Silt fraction (0.002–0.05mm) in root zone. Provides moisture storage and optimal plant-available water.",
    colorStops: createContourStops(18.0, 31.0),
  },
  soc: {
    id: "soc",
    name: "Soil Organic Carbon (SOC)",
    shortName: "SOC",
    nameKey: "dsm.layers.soc.name",
    descriptionKey: "dsm.layers.soc.desc",
    marathiName: "सेंद्रिय कर्ब (SOC)",
    unit: "%",
    category: "soil_properties",
    categoryLabel: "Soil Properties",
    categoryLabelMr: "मातीचे गुणधर्म",
    sourceType: "DSM PREDICTION",
    sourceLabel: "SoilGrids Standardized",
    status: "available",
    min: 0.6,
    max: 1.4,
    mean: 1.0,
    std: 0.12,
    description: "Organic carbon percentage in root zone. Keystone indicator of microbial biological activity & aggregate stability.",
    colorStops: createContourStops(0.6, 1.4),
  },
  nitrogen: {
    id: "nitrogen",
    name: "Available Nitrogen (N)",
    shortName: "Nitrogen",
    nameKey: "dsm.layers.nitrogen.name",
    descriptionKey: "dsm.layers.nitrogen.desc",
    marathiName: "उपलब्ध नत्र (N)",
    unit: "%",
    category: "soil_properties",
    categoryLabel: "Soil Properties",
    categoryLabelMr: "मातीचे गुणधर्म",
    sourceType: "DSM PREDICTION",
    sourceLabel: "SoilGrids Standardized",
    status: "available",
    min: 0.65,
    max: 1.25,
    mean: 1.04,
    std: 0.08,
    description: "Total Nitrogen concentration in the root zone. Crucial for leaf chlorophyll synthesis and crop vegetative growth.",
    colorStops: createContourStops(0.65, 1.25),
  },
  ph: {
    id: "ph",
    name: "Soil pH",
    shortName: "pH",
    nameKey: "dsm.layers.ph.name",
    descriptionKey: "dsm.layers.ph.desc",
    marathiName: "मातीचा सामू (pH)",
    unit: "pH",
    category: "soil_properties",
    categoryLabel: "Soil Properties",
    categoryLabelMr: "मातीचे गुणधर्म",
    sourceType: "DSM PREDICTION",
    sourceLabel: "SoilGrids Standardized",
    status: "available",
    min: 6.8,
    max: 7.4,
    mean: 7.15,
    std: 0.07,
    description: "Acidity / alkalinity (pH in H2O). Optimal neutral to slightly alkaline range for sugarcane & Deccan crops.",
    colorStops: createContourStops(6.8, 7.4),
  },
  soil_texture: {
    id: "soil_texture",
    name: "Soil Texture Classes",
    shortName: "Soil Texture",
    nameKey: "dsm.layers.soil_texture.name",
    descriptionKey: "dsm.layers.soil_texture.desc",
    marathiName: "मातीचा पोत / वर्ग",
    unit: "Class",
    category: "soil_properties",
    categoryLabel: "Soil Properties",
    categoryLabelMr: "मातीचे गुणधर्म",
    sourceType: "DSM PREDICTION",
    sourceLabel: "USDA / OpenLandMap Soil Texture Classification",
    status: "available",
    min: 1.0,
    max: 1.0,
    mean: 1.0,
    std: 0.0,
    description: "Standard USDA Soil Texture Classification (Class 1 = Clay / Deep Vertisols). Dominant black cotton agricultural soil.",
    colorStops: [
      { value: 1.0, color: "rgb(92, 61, 46)", label: "Class 1: Clay (काळी / चिकण माती)" },
    ],
  },

  // =========================================================================
  // 2. Topography & Elevation
  // =========================================================================
  elevation: {
    id: "elevation",
    name: "Digital Elevation Model (DEM)",
    shortName: "Elevation (DEM)",
    nameKey: "dsm.layers.elevation.name",
    descriptionKey: "dsm.layers.elevation.desc",
    marathiName: "डिजिटल एलिव्हेशन मॉडेल (DEM)",
    unit: "meters",
    category: "topography",
    categoryLabel: "Topography & Elevation",
    categoryLabelMr: "भूरूप आणि उंची",
    sourceType: "SATELLITE DERIVED",
    sourceLabel: "SRTM DEM 30m Resampled",
    status: "available",
    min: 541.0,
    max: 582.0,
    mean: 561.4,
    std: 7.8,
    description: "Surface elevation above mean sea level from high-resolution SRTM DEM. Drives surface hydrology and watershed drainage.",
    colorStops: createStopsFromColors(ELEVATION_COLORS, 541.0, 582.0),
  },
  slope: {
    id: "slope",
    name: "Slope Gradient",
    shortName: "Slope Gradient",
    nameKey: "dsm.layers.slope.name",
    descriptionKey: "dsm.layers.slope.desc",
    marathiName: "जमिनीचा उतार (Slope Gradient)",
    unit: "%",
    category: "topography",
    categoryLabel: "Topography & Elevation",
    categoryLabelMr: "भूरूप आणि उंची",
    sourceType: "SATELLITE DERIVED",
    sourceLabel: "SRTM Topographic Slope Analysis",
    status: "available",
    min: 0.0,
    max: 15.0,
    mean: 2.8,
    std: 2.1,
    description: "Topographic inclination percentage. Critical for estimating soil erosion risk, water runoff speed and terracing needs.",
    colorStops: createContourStops(0.0, 15.0, true),
  },

  // =========================================================================
  // 3. Land Use & Multi-Spectral Indices
  // =========================================================================
  lulc: {
    id: "lulc",
    name: "Land Use / Land Cover (Dynamic World)",
    shortName: "LULC",
    nameKey: "dsm.layers.lulc.name",
    descriptionKey: "dsm.layers.lulc.desc",
    marathiName: "जमीन वापर व आच्छादन (Dynamic World)",
    unit: "Class",
    category: "land_use",
    categoryLabel: "Land Use & Multi-Spectral Indices",
    categoryLabelMr: "जमीन वापर आणि बहु-स्पेक्ट्रल निर्देशांक",
    sourceType: "SATELLITE DERIVED",
    sourceLabel: "Dynamic World 10m (Sentinel-2)",
    status: "available",
    min: 0,
    max: 7,
    mean: 4.0,
    std: 1.0,
    description: "Near-real-time global 10m LULC classification by Dynamic World (WRI/Google): Crops, Built, Water, Trees, Shrub, Grass.",
    colorStops: [
      { value: 0, color: "rgb(65, 155, 223)", label: "Water (पाणी)" },
      { value: 1, color: "rgb(57, 125, 73)", label: "Trees (झाडे)" },
      { value: 2, color: "rgb(136, 176, 83)", label: "Grass (गवत)" },
      { value: 3, color: "rgb(122, 135, 198)", label: "Flooded Veg (जलमय वनस्पती)" },
      { value: 4, color: "rgb(228, 150, 53)", label: "Crops (पिके / शेती)" },
      { value: 5, color: "rgb(223, 195, 90)", label: "Shrub (झुडपे)" },
      { value: 6, color: "rgb(196, 40, 27)", label: "Built Area (बांधकाम)" },
    ],
  },
  kharif_rgb: {
    id: "kharif_rgb",
    name: "Kharif Season True-Color Composite",
    shortName: "Kharif Composite",
    nameKey: "dsm.layers.kharif_rgb.name",
    descriptionKey: "dsm.layers.kharif_rgb.desc",
    marathiName: "खरीप हंगाम नैसर्गिक रंग उपग्रह प्रतिमा",
    unit: "RGB",
    category: "land_use",
    categoryLabel: "Land Use & Multi-Spectral Indices",
    categoryLabelMr: "जमीन वापर आणि बहु-स्पेक्ट्रल निर्देशांक",
    sourceType: "SATELLITE DERIVED",
    sourceLabel: "Sentinel-2 (B4-B3-B2) Kharif Season",
    status: "available",
    min: 0.0,
    max: 1.0,
    mean: 0.5,
    std: 0.2,
    description: "Monsoon / Kharif season true-color optical satellite imagery composite from Sentinel-2 (Bands 4, 3, 2).",
    colorStops: [
      { value: 0.0, color: "rgb(40, 60, 40)", label: "Natural Ground Cover" },
      { value: 1.0, color: "rgb(220, 230, 200)", label: "High Reflectance Canopy" },
    ],
  },
  rabi_rgb: {
    id: "rabi_rgb",
    name: "Rabi Season True-Color Composite",
    shortName: "Rabi Composite",
    nameKey: "dsm.layers.rabi_rgb.name",
    descriptionKey: "dsm.layers.rabi_rgb.desc",
    marathiName: "रब्बी हंगाम नैसर्गिक रंग उपग्रह प्रतिमा",
    unit: "RGB",
    category: "land_use",
    categoryLabel: "Land Use & Multi-Spectral Indices",
    categoryLabelMr: "जमीन वापर आणि बहु-स्पेक्ट्रल निर्देशांक",
    sourceType: "SATELLITE DERIVED",
    sourceLabel: "Sentinel-2 (B4-B3-B2) Rabi Season",
    status: "available",
    min: 0.0,
    max: 1.0,
    mean: 0.5,
    std: 0.2,
    description: "Winter / Rabi season true-color optical satellite imagery composite from Sentinel-2 (Bands 4, 3, 2).",
    colorStops: [
      { value: 0.0, color: "rgb(40, 60, 40)", label: "Natural Ground Cover" },
      { value: 1.0, color: "rgb(220, 230, 200)", label: "High Reflectance Canopy" },
    ],
  },
  ndvi: {
    id: "ndvi",
    name: "Normalized Difference Vegetation Index (NDVI)",
    shortName: "NDVI",
    nameKey: "dsm.layers.ndvi.name",
    descriptionKey: "dsm.layers.ndvi.desc",
    marathiName: "वनस्पती निर्देशांक (NDVI)",
    unit: "index",
    category: "land_use",
    categoryLabel: "Land Use & Multi-Spectral Indices",
    categoryLabelMr: "जमीन वापर आणि बहु-स्पेक्ट्रल निर्देशांक",
    sourceType: "SATELLITE DERIVED",
    sourceLabel: "Sentinel-2 (10m)",
    status: "available",
    isDefault: true,
    min: 0.1,
    max: 0.75,
    mean: 0.398,
    std: 0.147,
    description: "Normalized Difference Vegetation Index from Sentinel-2. Measures crop vigor & canopy density.",
    colorStops: createContourStops(0.1, 0.75),
  },
  evi: {
    id: "evi",
    name: "Enhanced Vegetation Index (EVI)",
    shortName: "EVI",
    nameKey: "dsm.layers.evi.name",
    descriptionKey: "dsm.layers.evi.desc",
    marathiName: "वर्धित वनस्पती निर्देशांक (EVI)",
    unit: "index",
    category: "land_use",
    categoryLabel: "Land Use & Multi-Spectral Indices",
    categoryLabelMr: "जमीन वापर आणि बहु-स्पेक्ट्रल निर्देशांक",
    sourceType: "SATELLITE DERIVED",
    sourceLabel: "Sentinel-2 Enhanced",
    status: "available",
    min: 0.05,
    max: 0.55,
    mean: 0.23,
    std: 0.11,
    description: "Enhanced Vegetation Index. Reduced atmospheric and soil background interference for high biomass.",
    colorStops: createContourStops(0.05, 0.55),
  },
  savi: {
    id: "savi",
    name: "Soil-Adjusted Vegetation Index (SAVI)",
    shortName: "SAVI",
    nameKey: "dsm.layers.savi.name",
    descriptionKey: "dsm.layers.savi.desc",
    marathiName: "माती-समायोजित वनस्पती निर्देशांक (SAVI)",
    unit: "index",
    category: "land_use",
    categoryLabel: "Land Use & Multi-Spectral Indices",
    categoryLabelMr: "जमीन वापर आणि बहु-स्पेक्ट्रल निर्देशांक",
    sourceType: "SATELLITE DERIVED",
    sourceLabel: "Sentinel-2 SAVI (L=0.5)",
    status: "available",
    min: 0.05,
    max: 0.5,
    mean: 0.22,
    std: 0.1,
    description: "Adjusts for soil brightness influences in early vegetative or sparse canopy stages (L = 0.5 factor).",
    colorStops: createContourStops(0.05, 0.5),
  },
  ndmi: {
    id: "ndmi",
    name: "Normalized Difference Moisture Index (NDMI)",
    shortName: "NDMI",
    nameKey: "dsm.layers.ndmi.name",
    descriptionKey: "dsm.layers.ndmi.desc",
    marathiName: "ओलावा निर्देशांक (NDMI)",
    unit: "index",
    category: "land_use",
    categoryLabel: "Land Use & Multi-Spectral Indices",
    categoryLabelMr: "जमीन वापर आणि बहु-स्पेक्ट्रल निर्देशांक",
    sourceType: "SATELLITE DERIVED",
    sourceLabel: "Sentinel-2 (B8A-B11)",
    status: "available",
    min: -0.3,
    max: 0.4,
    mean: 0.05,
    std: 0.15,
    description: "Monitors crop canopy water content and root-zone soil moisture stress using NIR (B8A) and SWIR (B11).",
    colorStops: createStopsFromColors(MOISTURE_COLORS, -0.3, 0.4),
  },
  ndre: {
    id: "ndre",
    name: "Normalized Difference Red Edge (NDRE)",
    shortName: "NDRE",
    nameKey: "dsm.layers.ndre.name",
    descriptionKey: "dsm.layers.ndre.desc",
    marathiName: "रेड एज वनस्पती निर्देशांक (NDRE)",
    unit: "index",
    category: "land_use",
    categoryLabel: "Land Use & Multi-Spectral Indices",
    categoryLabelMr: "जमीन वापर आणि बहु-स्पेक्ट्रल निर्देशांक",
    sourceType: "SATELLITE DERIVED",
    sourceLabel: "Sentinel-2 Red Edge (10m)",
    status: "available",
    min: 0.05,
    max: 0.55,
    mean: 0.28,
    std: 0.12,
    description: "Uses Sentinel-2 RedEdge (B5/B7) for nitrogen content estimation without early saturation in thick sugarcane.",
    colorStops: createContourStops(0.05, 0.55),
  },
  bsi: {
    id: "bsi",
    name: "Bare Soil Index (BSI)",
    shortName: "BSI",
    nameKey: "dsm.layers.bsi.name",
    descriptionKey: "dsm.layers.bsi.desc",
    marathiName: "उघडी माती निर्देशांक (BSI)",
    unit: "index",
    category: "land_use",
    categoryLabel: "Land Use & Multi-Spectral Indices",
    categoryLabelMr: "जमीन वापर आणि बहु-स्पेक्ट्रल निर्देशांक",
    sourceType: "SATELLITE DERIVED",
    sourceLabel: "Sentinel-2 BSI (SWIR+Red / NIR+Blue)",
    status: "available",
    min: -0.2,
    max: 0.3,
    mean: 0.05,
    std: 0.12,
    description: "Differentiates bare agricultural soil from fallow ground, gravel and dense crop cover using SWIR + Blue bands.",
    colorStops: createContourStops(-0.2, 0.3, true),
  },
  ndwi: {
    id: "ndwi",
    name: "Normalized Difference Water Index (NDWI)",
    shortName: "NDWI",
    nameKey: "dsm.layers.ndwi.name",
    descriptionKey: "dsm.layers.ndwi.desc",
    marathiName: "पाणी निर्देशांक (NDWI)",
    unit: "index",
    category: "land_use",
    categoryLabel: "Land Use & Multi-Spectral Indices",
    categoryLabelMr: "जमीन वापर आणि बहु-स्पेक्ट्रल निर्देशांक",
    sourceType: "SATELLITE DERIVED",
    sourceLabel: "Sentinel-2 NDWI (McFeeters)",
    status: "available",
    min: -0.6,
    max: 0.2,
    mean: -0.25,
    std: 0.15,
    description: "Delineates open surface water bodies, canals, farm ponds and saturated wetland inundation zones.",
    colorStops: createStopsFromColors(MOISTURE_COLORS, -0.6, 0.2),
  },

  // Boundaries & Legacy
  farm_boundary: {
    id: "farm_boundary",
    name: "Cadastral Farm Boundary",
    shortName: "Gat Boundary",
    nameKey: "dsm.layers.boundary.name",
    descriptionKey: "dsm.layers.boundary.desc",
    marathiName: "शेत गट सीमा",
    unit: "",
    category: "soil_properties",
    sourceType: "DEMO KML",
    sourceLabel: "Land Records / Cadastral Map",
    status: "available",
    description: "Cadastral parcel boundaries with Gat numbers and area calculation.",
  },
  bd: {
    id: "bd",
    name: "Bulk Density",
    shortName: "Bulk Density",
    nameKey: "dsm.layers.bd.name",
    descriptionKey: "dsm.layers.bd.desc",
    marathiName: "मातीची घनता (Bulk Density)",
    unit: "g/cm³",
    category: "soil_properties",
    sourceType: "DSM PREDICTION",
    sourceLabel: "SoilGrids",
    status: "available",
    min: 1.25,
    max: 1.6,
    mean: 1.54,
    std: 0.04,
    description: "Dry mass of soil per unit volume (g/cm³).",
    colorStops: createContourStops(1.25, 1.6, true),
  },
  uncertainty: {
    id: "uncertainty",
    name: "DSM Prediction Uncertainty",
    shortName: "Uncertainty",
    nameKey: "dsm.layers.uncertainty.name",
    descriptionKey: "dsm.layers.uncertainty.desc",
    marathiName: "मॉडेल अनिश्चितता (Uncertainty)",
    unit: "% error",
    category: "soil_properties",
    sourceType: "DSM PREDICTION",
    sourceLabel: "Quantile Regression Forest",
    status: "available",
    min: 5.8,
    max: 10.5,
    mean: 7.2,
    std: 1.1,
    description: "Quantile Regression Forest 90% prediction interval error.",
    colorStops: createContourStops(5.8, 10.5, true),
  },
};

export const DSM_LAYER_LIST: DSMLayerConfig[] = DSM_LAYER_ORDER.map(
  (id) => DSM_LAYERS[id]
);
