import { DSMLayerConfig, DSMLayerId } from "@/types/gis";

export const DSM_LAYER_ORDER: DSMLayerId[] = [
  "ndvi",
  "evi",
  "ph",
  "soc",
  "nitrogen",
  "bd",
  "elevation",
  "uncertainty",
  "farm_boundary",
];

export const DSM_LAYERS: Record<DSMLayerId, DSMLayerConfig> = {
  ndvi: {
    id: "ndvi",
    name: "NDVI Vegetation Index",
    shortName: "NDVI",
    nameKey: "dsm.layers.ndvi.name",
    descriptionKey: "dsm.layers.ndvi.desc",
    marathiName: "वनस्पती निर्देशांक (NDVI)",
    unit: "index",
    category: "Organisms (O)",
    sourceType: "SATELLITE DERIVED",
    sourceLabel: "Sentinel-2 (10m)",
    status: "available",
    isDefault: true,
    min: 0.05,
    max: 0.76,
    mean: 0.398,
    std: 0.147,
    description: "Normalized Difference Vegetation Index from Sentinel-2. Measures crop vigor & canopy density.",
    colorStops: [
      { value: 0.05, color: "rgb(165, 0, 38)" },
      { value: 0.2, color: "rgb(244, 109, 67)" },
      { value: 0.38, color: "rgb(254, 254, 189)" },
      { value: 0.56, color: "rgb(102, 189, 99)" },
      { value: 0.76, color: "rgb(0, 104, 55)" },
    ],
  },
  evi: {
    id: "evi",
    name: "EVI Vegetation Index",
    shortName: "EVI",
    nameKey: "dsm.layers.evi.name",
    descriptionKey: "dsm.layers.evi.desc",
    marathiName: "वर्धित वनस्पती निर्देशांक (EVI)",
    unit: "index",
    category: "Organisms (O)",
    sourceType: "SATELLITE DERIVED",
    sourceLabel: "Sentinel-2 Enhanced",
    status: "available",
    min: 0.05,
    max: 0.7,
    mean: 0.23,
    std: 0.11,
    description: "Enhanced Vegetation Index. Reduced atmospheric and soil background interference for high biomass.",
    colorStops: [
      { value: 0.05, color: "rgb(255, 255, 204)" },
      { value: 0.25, color: "rgb(161, 218, 180)" },
      { value: 0.45, color: "rgb(65, 182, 196)" },
      { value: 0.7, color: "rgb(34, 94, 168)" },
    ],
  },
  ph: {
    id: "ph",
    name: "Soil pH (Reaction)",
    shortName: "pH",
    nameKey: "dsm.layers.ph.name",
    descriptionKey: "dsm.layers.ph.desc",
    marathiName: "जमिनीचा सामू (pH)",
    unit: "pH",
    category: "Soil Chemical (S)",
    sourceType: "DSM PREDICTION",
    sourceLabel: "QRF Model / Lab Calibrated",
    status: "available",
    min: 6.5,
    max: 8.5,
    mean: 7.35,
    std: 0.24,
    description: "Acidity / Alkalinity level (0-14 scale). Optimal range for Deccan vertisols is 6.5 - 7.8.",
    colorStops: [
      { value: 6.5, color: "rgb(215, 48, 39)" },
      { value: 7.0, color: "rgb(254, 224, 139)" },
      { value: 7.5, color: "rgb(166, 217, 106)" },
      { value: 8.0, color: "rgb(102, 194, 165)" },
      { value: 8.5, color: "rgb(49, 54, 149)" },
    ],
  },
  soc: {
    id: "soc",
    name: "Soil Organic Carbon (SOC)",
    shortName: "SOC",
    nameKey: "dsm.layers.soc.name",
    descriptionKey: "dsm.layers.soc.desc",
    marathiName: "सेंद्रिय कर्ब (SOC)",
    unit: "%",
    category: "Soil Chemical (S)",
    sourceType: "DSM PREDICTION",
    sourceLabel: "QRF Model (0-15cm)",
    status: "available",
    min: 0.2,
    max: 1.5,
    mean: 0.68,
    std: 0.18,
    description: "Organic Carbon percentage in topsoil (0-15 cm). Key driver of microbial health and nutrient buffering.",
    colorStops: [
      { value: 0.2, color: "rgb(255, 255, 212)" },
      { value: 0.5, color: "rgb(254, 217, 142)" },
      { value: 0.8, color: "rgb(254, 153, 41)" },
      { value: 1.2, color: "rgb(217, 95, 14)" },
      { value: 1.5, color: "rgb(153, 52, 4)" },
    ],
  },
  nitrogen: {
    id: "nitrogen",
    name: "Available Nitrogen (N)",
    shortName: "Nitrogen",
    nameKey: "dsm.layers.nitrogen.name",
    descriptionKey: "dsm.layers.nitrogen.desc",
    marathiName: "उपलब्ध नत्र (N)",
    unit: "mg/kg",
    category: "Primary Nutrient (S)",
    sourceType: "DSM PREDICTION",
    sourceLabel: "QRF Model",
    status: "available",
    min: 10.0,
    max: 25.0,
    mean: 14.8,
    std: 2.1,
    description: "Alkaline permanganate extractable Nitrogen (mg/kg). Equivalent to kg/ha (x2 factor).",
    colorStops: [
      { value: 10.0, color: "rgb(255, 255, 204)" },
      { value: 14.0, color: "rgb(161, 218, 180)" },
      { value: 18.0, color: "rgb(65, 182, 196)" },
      { value: 25.0, color: "rgb(37, 52, 148)" },
    ],
  },
  bd: {
    id: "bd",
    name: "Bulk Density",
    shortName: "Bulk Density",
    nameKey: "dsm.layers.bd.name",
    descriptionKey: "dsm.layers.bd.desc",
    marathiName: "घनता (Bulk Density)",
    unit: "g/cm³",
    category: "Soil Physical (S)",
    sourceType: "DSM PREDICTION",
    sourceLabel: "Pedotransfer / QRF",
    status: "available",
    min: 1.2,
    max: 1.8,
    mean: 1.48,
    std: 0.08,
    description: "Dry mass of soil per unit volume (g/cm³). Indicator of compaction, root penetration and aeration.",
    colorStops: [
      { value: 1.2, color: "rgb(0, 32, 77)" },
      { value: 1.4, color: "rgb(65, 105, 140)" },
      { value: 1.6, color: "rgb(180, 160, 120)" },
      { value: 1.8, color: "rgb(255, 235, 175)" },
    ],
  },
  elevation: {
    id: "elevation",
    name: "Elevation (DEM)",
    shortName: "Elevation",
    nameKey: "dsm.layers.elevation.name",
    descriptionKey: "dsm.layers.elevation.desc",
    marathiName: "उंची (Elevation)",
    unit: "m",
    category: "Relief (R)",
    sourceType: "SATELLITE DERIVED",
    sourceLabel: "SRTM 30m DEM",
    status: "available",
    min: 540.0,
    max: 600.0,
    mean: 565.0,
    std: 8.5,
    description: "Height above Mean Sea Level (m) derived from DEM. Controls hydrologic runoff & accumulation.",
    colorStops: [
      { value: 540.0, color: "rgb(51, 153, 51)" },
      { value: 560.0, color: "rgb(204, 204, 102)" },
      { value: 580.0, color: "rgb(153, 102, 51)" },
      { value: 600.0, color: "rgb(255, 255, 255)" },
    ],
  },
  uncertainty: {
    id: "uncertainty",
    name: "DSM Prediction Uncertainty",
    shortName: "Uncertainty",
    nameKey: "dsm.layers.uncertainty.name",
    descriptionKey: "dsm.layers.uncertainty.desc",
    marathiName: "मॉडेल अनिश्चितता (Uncertainty)",
    unit: "% error",
    category: "Model Quality (QRF)",
    sourceType: "DSM PREDICTION",
    sourceLabel: "Quantile Regression Forest",
    status: "available",
    min: 2.0,
    max: 20.0,
    mean: 7.2,
    std: 2.4,
    description: "Quantile Regression Forest 90% prediction interval error. Lower values represent higher confidence.",
    colorStops: [
      { value: 2.0, color: "rgb(0, 0, 4)" },
      { value: 7.0, color: "rgb(81, 18, 124)" },
      { value: 12.0, color: "rgb(182, 54, 121)" },
      { value: 16.0, color: "rgb(251, 136, 97)" },
      { value: 20.0, color: "rgb(252, 253, 191)" },
    ],
  },
  farm_boundary: {
    id: "farm_boundary",
    name: "Cadastral Farm Boundary",
    shortName: "Gat Boundary",
    nameKey: "dsm.layers.boundary.name",
    descriptionKey: "dsm.layers.boundary.desc",
    marathiName: "शेत गट सीमा",
    unit: "",
    category: "Cadastral",
    sourceType: "DEMO KML",
    sourceLabel: "Land Records / Cadastral Map",
    status: "available",
    description: "Cadastral parcel boundaries with Gat numbers and area calculation.",
  },
};

export const DSM_LAYER_LIST: DSMLayerConfig[] = DSM_LAYER_ORDER.map(
  (id) => DSM_LAYERS[id]
);
